version: '4.4.6'

services:
  mongodb:
    image: mongo:4.4.6
      #environment:
      #MONGO_INITDB_ROOT_USERNAME: user
    #MONGO_INITDB_ROOT_PASSWORD: password
    #MONGO_INITDB_DATABASE: mongoDB
    ports:
      - "27017:27017"
    container_name: "mongoDB"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: